<?php

/**
 * BaseSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $sitename
 * @property integer $hp_stranka_id
 * @property integer $hp_dolni_id
 * @property string $footer_text
 * @property string $email
 * @property string $tel
 * @property string $mobil
 * @property string $web_adr
 * @property string $ga_code
 * @property string $google_overeni
 * @property string $cs_slogan
 * @property clob $cs_pracovni_doba
 * @property string $cs_ulice
 * @property string $cs_mesto
 * @property string $en_slogan
 * @property clob $en_pracovni_doba
 * @property string $en_ulice
 * @property string $en_mesto
 * @property Stranka $Stranka
 * @property Stranka $Dolni
 * 
 * @method integer getId()               Returns the current record's "id" value
 * @method string  getSitename()         Returns the current record's "sitename" value
 * @method integer getHpStrankaId()      Returns the current record's "hp_stranka_id" value
 * @method integer getHpDolniId()        Returns the current record's "hp_dolni_id" value
 * @method string  getFooterText()       Returns the current record's "footer_text" value
 * @method string  getEmail()            Returns the current record's "email" value
 * @method string  getTel()              Returns the current record's "tel" value
 * @method string  getMobil()            Returns the current record's "mobil" value
 * @method string  getWebAdr()           Returns the current record's "web_adr" value
 * @method string  getGaCode()           Returns the current record's "ga_code" value
 * @method string  getGoogleOvereni()    Returns the current record's "google_overeni" value
 * @method string  getCsSlogan()         Returns the current record's "cs_slogan" value
 * @method clob    getCsPracovniDoba()   Returns the current record's "cs_pracovni_doba" value
 * @method string  getCsUlice()          Returns the current record's "cs_ulice" value
 * @method string  getCsMesto()          Returns the current record's "cs_mesto" value
 * @method string  getEnSlogan()         Returns the current record's "en_slogan" value
 * @method clob    getEnPracovniDoba()   Returns the current record's "en_pracovni_doba" value
 * @method string  getEnUlice()          Returns the current record's "en_ulice" value
 * @method string  getEnMesto()          Returns the current record's "en_mesto" value
 * @method Stranka getStranka()          Returns the current record's "Stranka" value
 * @method Stranka getDolni()            Returns the current record's "Dolni" value
 * @method Setting setId()               Sets the current record's "id" value
 * @method Setting setSitename()         Sets the current record's "sitename" value
 * @method Setting setHpStrankaId()      Sets the current record's "hp_stranka_id" value
 * @method Setting setHpDolniId()        Sets the current record's "hp_dolni_id" value
 * @method Setting setFooterText()       Sets the current record's "footer_text" value
 * @method Setting setEmail()            Sets the current record's "email" value
 * @method Setting setTel()              Sets the current record's "tel" value
 * @method Setting setMobil()            Sets the current record's "mobil" value
 * @method Setting setWebAdr()           Sets the current record's "web_adr" value
 * @method Setting setGaCode()           Sets the current record's "ga_code" value
 * @method Setting setGoogleOvereni()    Sets the current record's "google_overeni" value
 * @method Setting setCsSlogan()         Sets the current record's "cs_slogan" value
 * @method Setting setCsPracovniDoba()   Sets the current record's "cs_pracovni_doba" value
 * @method Setting setCsUlice()          Sets the current record's "cs_ulice" value
 * @method Setting setCsMesto()          Sets the current record's "cs_mesto" value
 * @method Setting setEnSlogan()         Sets the current record's "en_slogan" value
 * @method Setting setEnPracovniDoba()   Sets the current record's "en_pracovni_doba" value
 * @method Setting setEnUlice()          Sets the current record's "en_ulice" value
 * @method Setting setEnMesto()          Sets the current record's "en_mesto" value
 * @method Setting setStranka()          Sets the current record's "Stranka" value
 * @method Setting setDolni()            Sets the current record's "Dolni" value
 * 
 * @package    eracleamare
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSetting extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('setting');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('sitename', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('hp_stranka_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('hp_dolni_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('footer_text', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('tel', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('mobil', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('web_adr', 'string', 55, array(
             'type' => 'string',
             'length' => 55,
             ));
        $this->hasColumn('ga_code', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('google_overeni', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cs_slogan', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('cs_pracovni_doba', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('cs_ulice', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cs_mesto', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('en_slogan', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('en_pracovni_doba', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('en_ulice', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('en_mesto', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stranka', array(
             'local' => 'hp_stranka_id',
             'foreign' => 'id'));

        $this->hasOne('Stranka as Dolni', array(
             'local' => 'hp_dolni_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}