<?php

/**
 * BaseStranka
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $kategorie_id
 * @property integer $gallery_id
 * @property string $cs_title
 * @property string $cs_keywords
 * @property string $cs_description
 * @property clob $cs_perex
 * @property clob $cs_text
 * @property string $en_title
 * @property string $en_keywords
 * @property string $en_description
 * @property clob $en_perex
 * @property clob $en_text
 * @property Gallery $Gallery
 * @property Kategorie $Kategorie
 * @property Doctrine_Collection $Setting
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method integer             getKategorieId()    Returns the current record's "kategorie_id" value
 * @method integer             getGalleryId()      Returns the current record's "gallery_id" value
 * @method string              getCsTitle()        Returns the current record's "cs_title" value
 * @method string              getCsKeywords()     Returns the current record's "cs_keywords" value
 * @method string              getCsDescription()  Returns the current record's "cs_description" value
 * @method clob                getCsPerex()        Returns the current record's "cs_perex" value
 * @method clob                getCsText()         Returns the current record's "cs_text" value
 * @method string              getEnTitle()        Returns the current record's "en_title" value
 * @method string              getEnKeywords()     Returns the current record's "en_keywords" value
 * @method string              getEnDescription()  Returns the current record's "en_description" value
 * @method clob                getEnPerex()        Returns the current record's "en_perex" value
 * @method clob                getEnText()         Returns the current record's "en_text" value
 * @method Gallery             getGallery()        Returns the current record's "Gallery" value
 * @method Kategorie           getKategorie()      Returns the current record's "Kategorie" value
 * @method Doctrine_Collection getSetting()        Returns the current record's "Setting" collection
 * @method Stranka             setId()             Sets the current record's "id" value
 * @method Stranka             setName()           Sets the current record's "name" value
 * @method Stranka             setKategorieId()    Sets the current record's "kategorie_id" value
 * @method Stranka             setGalleryId()      Sets the current record's "gallery_id" value
 * @method Stranka             setCsTitle()        Sets the current record's "cs_title" value
 * @method Stranka             setCsKeywords()     Sets the current record's "cs_keywords" value
 * @method Stranka             setCsDescription()  Sets the current record's "cs_description" value
 * @method Stranka             setCsPerex()        Sets the current record's "cs_perex" value
 * @method Stranka             setCsText()         Sets the current record's "cs_text" value
 * @method Stranka             setEnTitle()        Sets the current record's "en_title" value
 * @method Stranka             setEnKeywords()     Sets the current record's "en_keywords" value
 * @method Stranka             setEnDescription()  Sets the current record's "en_description" value
 * @method Stranka             setEnPerex()        Sets the current record's "en_perex" value
 * @method Stranka             setEnText()         Sets the current record's "en_text" value
 * @method Stranka             setGallery()        Sets the current record's "Gallery" value
 * @method Stranka             setKategorie()      Sets the current record's "Kategorie" value
 * @method Stranka             setSetting()        Sets the current record's "Setting" collection
 * 
 * @package    eracleamare
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStranka extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stranka');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('kategorie_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cs_title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('cs_keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cs_description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('cs_perex', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('cs_text', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('en_title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('en_keywords', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('en_description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('en_perex', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('en_text', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id'));

        $this->hasOne('Kategorie', array(
             'local' => 'kategorie_id',
             'foreign' => 'id'));

        $this->hasMany('Setting', array(
             'local' => 'id',
             'foreign' => 'hp_stranka_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}