<?php

/**
 * KategorieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KategorieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KategorieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Kategorie');
    }
}