<?php

/**
 * Setting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    eracleamare
 * @subpackage model
 * @author     Jan Damek
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Setting extends BaseSetting {

    public function getSlogan() {
        global $sf_culture;
        if ($sf_culture == 'en') {
            return $this->getEnSlogan();
        }
        else
            return $this->getCsSlogan();
    }

    public function getMesto() {
        global $sf_culture;
        if ($sf_culture == 'en') {
            return $this->getEnMesto();
        }
        else
            return $this->getCsMesto();
    }

    public function getPracovniDoba() {
        global $sf_culture;
        if ($sf_culture == 'en') {
            return $this->getEnPracovniDoba();
        }
        else
            return $this->getCsPracovniDoba();
    }

    public function getUlice() {
        global $sf_culture;
        if ($sf_culture == 'en') {
            return $this->getEnUlice();
        }
        else
            return $this->getCsUlice();
    }

}
