<?php

/**
 * StrankaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StrankaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StrankaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Stranka');
    }
}