<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/28 11:28:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=komunikujeme',
  'username' => 'root',
  'password' => 'SQLserverAT',
  'attributes' => 
  array (
    'default_table_collate' => 'utf8_czech_ci',
    'default_table_charset' => 'utf8',
  ),
  'name' => 'doctrine',
)),);
