<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/28 11:38:35
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_sf_admin_theme_jroller_plugin_web_dir' => '/sfAdminThemejRollerPlugin',
  'app_sf_admin_theme_jroller_plugin_use_jquery' => true,
  'app_sf_admin_theme_jroller_plugin_theme_dir' => '/sfAdminThemejRollerPlugin/css/jquery',
  'app_sf_admin_theme_jroller_plugin_theme' => 'redmond',
  'app_sf_admin_theme_jroller_plugin_theme_switcher' => false,
  'app_sf_admin_theme_jroller_plugin_css_reset' => true,
  'app_sf_admin_theme_jroller_plugin_list_actions_position' => 'left',
  'app_sf_admin_theme_jroller_plugin_edit_tab_position' => 'vertical',
  'app_sf_admin_theme_jroller_plugin_icons' => array (
  'new' => 'plus',
  'filter' => 'check',
  'filters' => 'search',
  'reset' => 'circle-close',
  'show' => 'document',
  'edit' => 'pencil',
  'delete' => 'trash',
  'list' => 'arrowreturnthick-1-w',
  'save' => 'circle-check',
  'saveAndAdd' => 'circle-plus',
  'first' => 'seek-first',
  'previous' => 'seek-prev',
  'next' => 'seek-next',
  'last' => 'seek-end',
),
  'app_sf_media_browser_root_dir' => '/tests-uploads',
  'app_sf_media_browser_thumbnails_enabled' => true,
  'app_sf_media_browser_thumbnails_dir' => '.thumbnails',
  'app_sf_media_browser_thumbnails_max_width' => 64,
  'app_sf_media_browser_thumbnails_max_height' => 64,
  'app_sf_media_browser_assets_list' => array (
  'js' => 
  array (
    0 => '/js/jquery.js',
    1 => '/js/jquery.dragndrop.js',
    2 => '/sfMediaBrowserPlugin/js/list.jquery.js',
  ),
  'css' => 
  array (
    0 => '/sfMediaBrowserPlugin/css/list.css',
  ),
),
  'app_sf_media_browser_assets_widget' => array (
  'js' => 
  array (
    0 => '/sfMediaBrowserPlugin/js/WindowManager.js',
    1 => '/sfMediaBrowserPlugin/js/form_widget.js',
  ),
  'css' => 
  array (
    0 => '/sfMediaBrowserPlugin/css/form_widget.css',
  ),
),
  'app_sf_media_browser_file_types' => array (
  'document' => 
  array (
    'extensions' => 
    array (
      0 => 'doc',
      1 => 'xls',
      2 => 'xcf',
      3 => 'ai',
    ),
    'icon' => 'doc',
  ),
  'image' => 
  array (
    'extensions' => 
    array (
      0 => 'png',
      1 => 'jpg',
      2 => 'jpeg',
      3 => 'gif',
    ),
  ),
  'pdf' => 
  array (
    'extensions' => 
    array (
      0 => 'pdf',
    ),
  ),
  'bin' => 
  array (
    'extensions' => 
    array (
      0 => 'bin',
      1 => 'exe',
      2 => 'sh',
      3 => 'bat',
      4 => 'deb',
      5 => 'yum',
    ),
  ),
  'video' => 
  array (
    'extensions' => 
    array (
      0 => 'wmv',
      1 => 'avi',
      2 => 'mpg',
      3 => 'mpeg',
      4 => 'flv',
      5 => 'mp4',
    ),
  ),
  'audio' => 
  array (
    'extensions' => 
    array (
      0 => 'ogg',
      1 => 'mp3',
      2 => 'flac',
      3 => 'wma',
      4 => 'cda',
    ),
  ),
  'text' => 
  array (
    'extensions' => 
    array (
      0 => 'txt',
    ),
  ),
  'tarball' => 
  array (
    'extensions' => 
    array (
      0 => 'tar',
      1 => 'gz',
      2 => 'zip',
      3 => 'bzip',
      4 => 'gzip',
      5 => 'rar',
      6 => '7z',
    ),
  ),
),
));
